export const MonitoringPermission = {
  MONITORING_CONNECTIVITY_PROBE_SETTINGS: "MONITORING_CONNECTIVITY_PROBE_SETTINGS",
  MONITORING_BOX_PING_VIEW: "MONITORING_BOX_PING_VIEW",
  MONITORING_LOGS_VIEW: "MONITORING_LOGS_VIEW",
  MONITORING_SCHEDULER_VIEW: "MONITORING_SCHEDULER_VIEW",
  MONITORING_TESTING_VIEW: "MONITORING_TESTING_VIEW",
  MONITORING_TESTING_EXECUTE: "MONITORING_TESTING_EXECUTE",
  MONITORING_SMART_PLUG_VIEW: "MONITORING_SMART_PLUG_VIEW",
  MONITORING_SMART_PLUG_INVENTORY_CREATE: "MONITORING_SMART_PLUG_INVENTORY_CREATE",
  MONITORING_SMART_PLUG_INVENTORY_EDIT: "MONITORING_SMART_PLUG_INVENTORY_EDIT",
  MONITORING_SMART_PLUG_INVENTORY_DELETE: "MONITORING_SMART_PLUG_INVENTORY_DELETE",
  MONITORING_SMART_PLUG_ASSIGN_MONITOR: "MONITORING_SMART_PLUG_ASSIGN_MONITOR",
  MONITORING_SMART_PLUG_ASSIGN_BOX: "MONITORING_SMART_PLUG_ASSIGN_BOX",
  MONITORING_SMART_PLUG_ACCOUNTS_MANAGE: "MONITORING_SMART_PLUG_ACCOUNTS_MANAGE",
  MONITORING_SMART_PLUG_DISCOVERY_RUN: "MONITORING_SMART_PLUG_DISCOVERY_RUN",
  MONITORING_SMART_PLUG_TEST_READ: "MONITORING_SMART_PLUG_TEST_READ",
  MONITORING_SMART_PLUG_HISTORY_VIEW: "MONITORING_SMART_PLUG_HISTORY_VIEW",
  MONITORING_SMART_PLUG_LOGS_VIEW: "MONITORING_SMART_PLUG_LOGS_VIEW",
  ADMIN_CLIENTS_DEACTIVATE: "ADMIN_CLIENTS_DEACTIVATE",
} as const;

export type MonitoringPermissionCode =
  (typeof MonitoringPermission)[keyof typeof MonitoringPermission];
