export const MonitoringPermission = {
  MONITORING_LOGS_VIEW: "MONITORING_LOGS_VIEW",
  MONITORING_SCHEDULER_VIEW: "MONITORING_SCHEDULER_VIEW",
  MONITORING_TESTING_VIEW: "MONITORING_TESTING_VIEW",
  MONITORING_TESTING_EXECUTE: "MONITORING_TESTING_EXECUTE",
  MONITORING_SMART_PLUG_ADMIN: "MONITORING_SMART_PLUG_ADMIN",
  ADMIN_CLIENTS_DEACTIVATE: "ADMIN_CLIENTS_DEACTIVATE",
} as const;

export type MonitoringPermissionCode =
  (typeof MonitoringPermission)[keyof typeof MonitoringPermission];
