export enum ReferenciaNotificacao {
  APROVACAO_DOCUMENTO_CADASTRO,
  RECUSA_DOCUMENTO_CADASTRO,
  APROVACAO_DOCUMENTO_OFERTA,
  RECUSA_DOCUMENTO_OFERTA,
  OFERTA_AVALIADA,
  PEDIDO_RECEBIDO,
  ATUALIZACAO_STATUS_PEDIDO
}
